sonar.projectKey=Malzap12_stayhub-web
sonar.organization=malzap12
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts
sonar.coverage.exclusions=**/*.model.ts,src/main.ts,src/styles.css
sonar.cpd.exclusions=**/*.model.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
